[dc2_spines]
A-SPINE-01  ansible_host=192.168.1.30
A-SPINE-02  ansible_host=192.168.1.31

[dc2_leaves]
A-LEAF-01   ansible_host=192.168.1.32
A-LEAF-02   ansible_host=192.168.1.33
A-LEAF-03   ansible_host=192.168.1.34
A-LEAF-04   ansible_host=192.168.1.35

[dc2_border]
A-LEAF-05   ansible_host=192.168.1.36

[dc2_fabric:children]
dc2_spines
dc2_leaves
dc2_border

[dc2_esi_pair1]
A-LEAF-01   ansible_host=192.168.1.32
A-LEAF-02   ansible_host=192.168.1.33

[dc2_esi_pair2]
A-LEAF-03   ansible_host=192.168.1.34
A-LEAF-04   ansible_host=192.168.1.35

[dc2_servers]
A-SRV-1     ansible_host=192.168.1.50
A-SRV-2     ansible_host=192.168.1.51
A-SRV-3     ansible_host=192.168.1.53
A-SRV-4     ansible_host=192.168.1.52

[dc2_ios:children]
dc2_servers

[dc2:children]
dc2_fabric
dc2_ios
