---
hostname: A-LEAF-03
role: leaf
loopback0_ip: "10.1.0.13/32"
loopback1_ip: "10.1.0.113/32"
router_id: "10.1.0.13"
bgp_router_id: "10.1.0.13"
mgmt_ip: "192.168.1.34/24"
mgmt_gw: "192.168.1.1"
underlay_interfaces:
  - { name: Ethernet1, description: to_A-SPINE-01_Eth3, ip: "172.16.3.5/31" }
  - { name: Ethernet2, description: to_A-SPINE-02_Eth3, ip: "172.16.4.5/31" }
esi_enabled: true
esi_server_ports:
  - po_id: 3
    esi: "0000:0000:0000:0000:0003"
    lacp_id: "0000.0000.0003"
    vlan: 10
    description: A-SRV-3-TENANT-A
    interfaces: [Ethernet3]
  - po_id: 4
    esi: "0000:0000:0000:0000:0004"
    lacp_id: "0000.0000.0004"
    vlan: 20
    description: A-SRV-4-TENANT-B
    interfaces: [Ethernet4]
