[dc1_spines]
N-SPINE-01  ansible_host=192.168.1.10
N-SPINE-02  ansible_host=192.168.1.11

[dc1_leaves]
N-LEAF-01   ansible_host=192.168.1.12
N-LEAF-02   ansible_host=192.168.1.13
N-LEAF-03   ansible_host=192.168.1.14
N-LEAF-04   ansible_host=192.168.1.15

[dc1_border]
N-LEAF-05   ansible_host=192.168.1.16

[dc1_fabric:children]
dc1_spines
dc1_leaves
dc1_border

[dc1_vpc_pair1]
N-LEAF-01   ansible_host=192.168.1.12
N-LEAF-02   ansible_host=192.168.1.13

[dc1_vpc_pair2]
N-LEAF-03   ansible_host=192.168.1.14
N-LEAF-04   ansible_host=192.168.1.15

[dc1_servers]
SRV1-TEN-A  ansible_host=192.168.1.54
SRV1-TEN-B  ansible_host=192.168.1.55
SRV2-TEN-A  ansible_host=192.168.1.56
SRV2-TEN-B  ansible_host=192.168.1.57

[pcs]
PC1-TEN-A   ansible_host=192.168.1.23
PC2-TEN-B   ansible_host=192.168.1.24

[external]
R-ISP       ansible_host=192.168.1.17
SW          ansible_host=192.168.1.18

[dc1_ios:children]
dc1_servers
pcs
external

[dc1:children]
dc1_fabric
dc1_ios
