[dc1_spines]
N-SPINE-01  ansible_host=192.168.1.10
N-SPINE-02  ansible_host=192.168.1.11

[dc1_leaves]
N-LEAF-01   ansible_host=192.168.1.12
N-LEAF-02   ansible_host=192.168.1.13
N-LEAF-03   ansible_host=192.168.1.14
N-LEAF-04   ansible_host=192.168.1.15

[dc1_border]
N-LEAF-05   ansible_host=192.168.1.16

[dc1_fabric:children]
dc1_spines
dc1_leaves
dc1_border

[dc2_spines]
A-SPINE-01  ansible_host=192.168.1.30
A-SPINE-02  ansible_host=192.168.1.31

[dc2_leaves]
A-LEAF-01   ansible_host=192.168.1.32
A-LEAF-02   ansible_host=192.168.1.33
A-LEAF-03   ansible_host=192.168.1.34
A-LEAF-04   ansible_host=192.168.1.35

[dc2_border]
A-LEAF-05   ansible_host=192.168.1.36

[dc2_fabric:children]
dc2_spines
dc2_leaves
dc2_border

[dc1_servers]
SRV1-TEN-A  ansible_host=192.168.1.54
SRV1-TEN-B  ansible_host=192.168.1.55
SRV2-TEN-A  ansible_host=192.168.1.56
SRV2-TEN-B  ansible_host=192.168.1.57

[dc2_servers]
A-SRV-1     ansible_host=192.168.1.50
A-SRV-2     ansible_host=192.168.1.51
A-SRV-3     ansible_host=192.168.1.52
A-SRV-4     ansible_host=192.168.1.53

[pcs]
PC1-TEN-A   ansible_host=192.168.1.23
PC2-TEN-B   ansible_host=192.168.1.24

[external]
R-ISP       ansible_host=192.168.1.17
SW          ansible_host=192.168.1.18

[dc1_security]
PaloAlto-FW1  ansible_host=192.168.1.40
Fortinet-FW1  ansible_host=192.168.1.58
BIGIP-LB1     ansible_host=192.168.1.71

[dc2_security]
Fortinet-FW2  ansible_host=192.168.1.59
PaloAlto-FW2  ansible_host=192.168.1.44
BIGIP-LB2     ansible_host=192.168.1.72

[dc1_ios:children]
dc1_servers
pcs
external

[dc2_ios:children]
dc2_servers

[fabric:children]
dc1_fabric
dc2_fabric

[lab:children]
fabric
dc1_ios
dc2_ios
dc1_security
dc2_security
