[spines]
SPINE-01  ansible_host=192.168.1.10
SPINE-02  ansible_host=192.168.1.11

[leaves]
LEAF-01   ansible_host=192.168.1.12
LEAF-02   ansible_host=192.168.1.13
LEAF-03   ansible_host=192.168.1.14
LEAF-04   ansible_host=192.168.1.15

[border_leaf]
LEAF-05   ansible_host=192.168.1.16

[fabric:children]
spines
leaves
border_leaf

[vpc_pair_1]
LEAF-01   ansible_host=192.168.1.12
LEAF-02   ansible_host=192.168.1.13

[vpc_pair_2]
LEAF-03   ansible_host=192.168.1.14
LEAF-04   ansible_host=192.168.1.15

[servers]
SRV1-TEN-A  ansible_host=192.168.1.19
SRV1-TEN-B  ansible_host=192.168.1.20
SRV2-TEN-A  ansible_host=192.168.1.21
SRV2-TEN-B  ansible_host=192.168.1.22

[pcs]
PC1-TEN-A   ansible_host=192.168.1.23
PC2-TEN-B   ansible_host=192.168.1.24

[external]
R-ISP     ansible_host=192.168.1.17
SW        ansible_host=192.168.1.18

[ios_devices:children]
external
servers
pcs

[lab:children]
fabric
ios_devices
